# For more information: https://laravel.com/docs/sail
version: '3'
services:
  aboutlaravel:
    build:
        context: ./
        dockerfile: Dockerfile
        args:
            user: husni
            uid: 1000
    image: aboutlaravel
    ports:
        - '80:80'
    volumes:
        - '.:/var/www'
    networks:
        - aboutlaravel

  db:
    image: mysql:latest
    container_name: aboutlaravel-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - aboutlaravel

  nginx:
    image: nginx:alpine
    container_name: aboutlaravel-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - aboutlaravel
networks:
    aboutlaravel:
        driver: bridge

